### ISSUE TITLE
error enabling the plugin

### ISSUE THREAD

**Issue by jmls** [bruj0/vault-plugin-auth-u2f#1]
I know I must be doing something stupid, but can't get the plugin to load

```
/ # vault plugin register -sha256=c2ab819bf43aba52230b6a7447ceeac9404fa6035bb0e834152d0d641a488aee -command=u2f auth u2f
Success! Registered plugin: u2f
/ # vault plugin info auth u2f
Key        Value
---        -----
args       []
builtin    false
command    u2f
name       u2f
sha256     c2ab819bf43aba52230b6a7447ceeac9404fa6035bb0e834152d0d641a488aee
/ # ls -l /vault/plugins
total 24640
-rwxr-xr-x    1 522411   89939     12328960 Mar 17 11:09 u2f
-rw-r--r--    1 root     root            65 Mar 17 11:22 u2f.shasum
/ # vault auth enable u2f
Error enabling u2f auth: Error making API request.

URL: POST http://127.0.0.1:8200/v1/sys/auth/u2f
Code: 400. Errors:

* fork/exec /vault/plugins/u2f: no such file or directory
/ # 

```

as you can see, it seems to register ok, but fails when trying to enable the plugin

Would appreciate someone telling me where I am going wrong ;)

**Comment by bruj0** [comment]
Hi, since you know this file exists `/vault/plugins/u2f` then Vault is either looking for it in the wrong place or it doesnt have access to it.
Is it running under Docker? If so can you share the Dockerfile?

**Comment by jmls** [comment]
I am using other external plugins, which are in the same plugin directory. It may be that the binary is not suitable for alpine, so I'm trying to build an alpine version. (Hence ticket #2 )

Will let you know if that solves this issue

**Comment by jmls** [comment]
this is definitely related to the binary. When I've recompiled using alpine as the platform then the auth enable works without error
