### ISSUE TITLE
obtaining value for device

### ISSUE THREAD

**Issue by jmls** [bruj0/vault-plugin-auth-u2f#3]
in the registration request you make this post

`req, statusCode := postPasstrough("auth/u2f/registerRequest/mydevice", []byte(dataJSON))`

where "mydevice" I presume is a string identifier for the hardware key . How would you implement this in production if there are hundreds of users ? If this is being used as the primary login , then there is no user-identifying string that could be used pre-login , unless you can get an ID from the key itself

Curious minds want to know ;)

**Comment by bruj0** [comment]
That is part of the **demo** frontend, its not meant to be used anywhere else.

**Comment by jmls** [comment]
yes, I understand that , this is why I asked the question ;) 

I was wondering how to implement this in production . What exactly is "mydevice" ? Is it a unique identifier ? is it a random string ? Is it unique to the key or the user ?

**Comment by bruj0** [comment]
This is explained, perhaps poorly, in the Registration part of the readme.

https://github.com/bruj0/vault-plugin-auth-u2f#registrations

Its meant to be the friendly name given to the physical token when an administrator "registers" it in Vault.

Internally its the unique ID that will be used as a key to save all the data for future authentication.

There is no expected format, only that its in simple ascii format.

**Comment by jmls** [comment]
ok, thanks for that. I see that it's also used in the login request. Which means that the "client" (browser / user) has to know this name in advance. (ie it is part of both the reigstration and login url)

Which kinda brings me back to the original question : how would I know what this friendly name is if the user hasn't logged in ?  

I'm thinking that there should be an input field for "name" or something like that - I'm thinking of using an email address . Would that work ?

**Comment by bruj0** [comment]
Oh I see what you mean. The person to be authenticated would also need to know this "friendly name" of the device, then yes an email would be perfect. Just replace the `@` for %40 so its url safe. 

So the UI would ask you for your "ID", use it as the device name and then send it along in the APIs call, ie auth/u2f/signRequest/<ID>

**Comment by bruj0** [comment]
Ive enabled Discussions in case you have more questions/comments!

https://github.com/bruj0/vault-plugin-auth-u2f/discussions
